### ISSUE TITLE
Gnome 46 Support

### ISSUE THREAD

**Issue by PorteBannana** [codilia/upower-battery#16]
It would be nice to add Gnome 46 support.

**Comment by ppiastucki** [comment]
It'll be added as soon as Ubuntu 24.04 is out.

**Comment by valdrin-hoti** [comment]
Hello everyone,
As Gnome 46 is now the default in both Fedora 40 and Ubuntu 24.04, could we get an update on the status of this issue? 

Thanks!

**Comment by ppiastucki** [comment]
Added in v19
