### ISSUE TITLE
Apple Magic Trackpad

### ISSUE THREAD

**Issue by Tealk** [codilia/upower-battery#5]
Hello,

why is the Apple trackpad not shown even though Gnome shows it in the settings?

![image](https://user-images.githubusercontent.com/12276250/199226971-99c7903e-ea84-4f0d-a403-6f4872866e92.png)

**Comment by ppiastucki** [comment]
Please try:
```
upower -d | egrep 'mouse|keyboard' -A 7
```
and see if it returns the device.
If not try:
```
upower -d
```
find the device in the list and provide the respective section, something like:
```Device: /org/freedesktop/UPower/devices/keyboard_dev_D5_C1_6A_5C_1E_94
  native-path:          /org/bluez/hci0/dev_D5_C1_6A_5C_1E_94
  model:                MX Keys
  serial:               D5:C1:6A:5C:1E:94
  power supply:         no
  updated:              wto, 1 lis 2022, 09:13:32 (16894 seconds ago)
  has history:          yes
  has statistics:       no
  keyboard
    present:             yes
    rechargeable:        no
    state:               unknown
    warning-level:       none
    percentage:          50%
    icon-name:          'battery-missing-symbolic'
```

**Comment by Tealk** [comment]
Probably not identified as a mouse or keyboard
```
Device: /org/freedesktop/UPower/devices/battery_hid_18o7eob9o67of4o86_battery
  native-path:          hid-18:7e:b9:67:f4:86-battery
  model:                Tealk-Magic Trackpad 2
  power supply:         no
  updated:              Di 01 Nov 2022 14:36:49 CET (3 seconds ago)
  has history:          yes
  has statistics:       yes
  touchpad
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    percentage:          15%
    icon-name:          'battery-caution-symbolic'
```

**Comment by ppiastucki** [comment]
@Tealk Could you apply the following change locally and let me know if it works: https://github.com/codilia/upower-battery/commit/f34ea939158677e443de82efaad403530a9bcc74?

**Comment by Tealk** [comment]
Do I have to reload the extension somehow specifically, because with the one line nothing happens yet

**Comment by ppiastucki** [comment]
ALT+F2, type R and press Enter to restart the Gnome Shell or simply log out and log in again. This should be enough.

**Comment by Tealk** [comment]
The reload does not work under Wayland, but after I have re-logged I see the trackpad in the bar
Thank you :D

**Comment by ppiastucki** [comment]
Thank you very much for your help. I will include the change in the next release later this week.

**Comment by Tealk** [comment]
can you add colors? so that the icon turns red at e.g. 10%?

**Comment by ppiastucki** [comment]
Thank you for the suggestion. I am closing this issue but I will look into adding coloured icons
