### ISSUE TITLE
battery indicator not very accurate

### ISSUE THREAD

**Issue by Tealk** [codilia/upower-battery#7]
Hi,

it's probably not an extension problem, but maybe you know a solution.
The Apple Touchpad shows every single percent when charging and discharging.
The Logitech MX Keys has been at 100% for ages and I don't think it's that low on power that it's been like this for days.
Is there a way that the number on the keyboard are also so accurate?

**Comment by ppiastucki** [comment]
Please report the problems to upower team (https://gitlab.freedesktop.org/upower/upower) as the indicator simply shows the information provided by upower.
